### ISSUE TITLE
How to get VOC signal in PPM

### ISSUE THREAD

**Issue by marcovilla118** [Sensirion/arduino-gas-index-algorithm#4]
Dear All,

somebody know how to extract from the raw signal the ppb values? at least for the VOC.

Best Regards

**Comment by quentin-cy** [comment]
Hello @marcovilla118 ,
It is not possible to get a reliable PPM reading from the raw value of a sensor when used outside of a controlled environment.
See that [document](https://www.sensirion.com/media/documents/D27F03C0/6294E00F/Info_Note_Output_MOX_Sensor.pdf) for a more complete explanation.
You can either user the RAW signal (internal resistance of the sensor) or use the output of the algorithm (which gives a usable output)

I hope my answer is clear :)

Cheers
Quentin

**Comment by marcovilla118** [comment]
Hi, 
yes you are clear, and thank for your rapid answer.
I would like to use the sensor to measure ethanol in clean air in a controlled environment, so this is why I would like to understand the "formula" to calculate the ppb concentration starting from the RAW signal. Of course my environment is basically clean air and ethanol from 0 to 3000ppb. 
Do you know which formula I can use?
Thanks

**Comment by quentin-cy** [comment]
Hello @marcovilla118 ,
I see... Unfortunately I can not help you much there.

You will need to find the conversion function yourself through experimentation. 
I guess you would need to take several measurements at known concentrations then apply some interpolation to extract your conversion function.

Sorry that I do not have  a pre-computed conversion function for you :/

Hope you will achieve what you want
Cheers
Q

:warning: **Important note, this is not a usage Sensirion recommends** :warning: 
Because of how MOX technology works, your conversion function will only apply to a specific sensor (calibration is sensor specific). Please also note that the calibration will drift over time because of sensor polution
